export const agentConfig = {
  workspaceRoot: process.cwd(),
  maxTurns: 5,
  defaultOpenAIModel: "gpt-4-turbo-preview",
  terminalTimeoutMs: 120_000,
  terminalMaxBufferBytes: 1024 * 1024,
  terminalAllowedCommandPatterns: [
    /^npm\s+(test|run|install|ci|ls|list|view|audit)(\s|$)/i,
    /^npx\s+[\w@./-]+(\s|$)/i,
    /^node\s+(-v|--version|[\w./-]+)(\s|$)/i,
    /^tsc(\s|$)/i,
    /^mvn\s+[\w:./=@-]+(\s|$)/i,
    /^git\s+(status|diff|log|show|branch|rev-parse)(\s|$)/i,
    /^rg\s+.+/i,
    /^dir(\s|$)/i,
    /^ls(\s|$)/i,
  ],
  autoHealMaxAttempts: 2,
  memoryDirName: ".nexus",
  memoryFileName: "history.json",
  sessionMemoryDirName: "sessions",
  auditRunDirName: "runs",
  auditMaxValueLength: 4000,
  projectMapMaxFiles: 200,
  projectMapIgnoredDirs: new Set([".git", ".nexus", ".tmp-build", ".tmp-test", "dist", "node_modules"]),
} as const;
